apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress-{{ .Values.application.name }}"
spec:
  rules:
    - http:
        paths:
          - path: /hello
            pathType: Exact
            backend:
              service:
                name: 'svc-{{ .Values.application.name }}'
                port:
                  number: {{ .Values.service.port }}
