apiVersion: v1
kind: Service
metadata:
  name: "svc-{{ .Values.application.name }}"
  labels:
    application: {{ .Values.application.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    application: {{ .Values.application.name }}
